name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run Jest tests
        run: npm run test -- --ci

      - name: Build app
        run: npm run build

      - name: Start app in background
        run: |
          nohup npm run start &>/dev/null &
          npx wait-on http://localhost:3000 -t 60000

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test tests/playwright
      - name: Build Docker image
        run: docker build -t rajat864/dummy-sdlc:latest .

      - name: Push Docker image
        run: docker push rajat864/dummy-sdlc:latest